# 下载数据包


In [1]:
import  urllib.request
import os
data_url='http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.xls'
data_file_path='data/titanic3.xls'
if not os.path.isfile(data_file_path):
    result=urllib.request.urlretrieve(data_url,data_file_path)
    print('downloaded:',result)
else:
    print(data_file_path,'data file already exists.')

data/titanic3.xls data file already exists.


# 使用pandas进行数据处理

In [2]:
import numpy
import pandas as pd
#读取数据，结果为DataFrame格式
df_data=pd.read_excel(data_file_path)

In [3]:
#查看摘要
df_data.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [4]:
df_data

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

# 筛选提取需要特征字段
survival 是否存在字段
筛选去需要特征字段，去掉ticket，cabin

In [5]:
# 筛选特征字段
selected_cols=['survived','name','pclass','sex','age','sibsp','parch','fare','embarked']
selected_df_data=df_data[selected_cols]

In [6]:
selected_df_data

survived                                             name  pclass  \
0            1                    Allen, Miss. Elisabeth Walton       1   
1            1                   Allison, Master. Hudson Trevor       1   
2            0                     Allison, Miss. Helen Loraine       1   
3            0             Allison, Mr. Hudson Joshua Creighton       1   
4            0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1   
...        ...                                              ...     ...   
1304         0                             Zabour, Miss. Hileni       3   
1305         0                            Zabour, Miss. Thamine       3   
1306         0                        Zakarian, Mr. Mapriededer       3   
1307         0                              Zakarian, Mr. Ortin       3   
1308         0                               Zimmerman, Mr. Leo       3   

         sex      age  sibsp  parch      fare embarked  
0     female  29.0000      0      0  211.3375        S  
1       male   0.9167      1      2  151.5500        S  
2     female   2.0000      1      2  151.5500        S  
3       male  30.0000      1      2  151.5500        S  
4     female  25.0000      1      2  151.5500        S  
...      ...      ...    ...    ...       ...      ...  
1304  female  14.5000      1      0   14.4542        C  
1305  female      NaN      1      0   14.4542        C  
1306    male  26.5000      0      0    7.2250        C  
1307    male  27.0000      0      0    7.2250        C  
1308    male  29.0000      0      0    7.8750        S  

[1309 rows x 9 columns]

# 处理缺失值

In [7]:
# 找出有null字段
#Pandas判断缺失值一般采用isnull（），生成所有数据的True，False矩阵
# 这是元素判别的判断，把对应所有元素位置都列出来，元素为空或者Na就显示True，否则就False
selected_df_data.isnull()

survived   name  pclass    sex    age  sibsp  parch   fare  embarked
0        False  False   False  False  False  False  False  False     False
1        False  False   False  False  False  False  False  False     False
2        False  False   False  False  False  False  False  False     False
3        False  False   False  False  False  False  False  False     False
4        False  False   False  False  False  False  False  False     False
...        ...    ...     ...    ...    ...    ...    ...    ...       ...
1304     False  False   False  False  False  False  False  False     False
1305     False  False   False  False   True  False  False  False     False
1306     False  False   False  False  False  False  False  False     False
1307     False  False   False  False  False  False  False  False     False
1308     False  False   False  False  False  False  False  False     False

[1309 rows x 9 columns]

In [8]:
#判断哪些列有缺失值
#这是元素级别的判断。把对应所有元素位置都列出来，元素为空或者NA就是True，否则就是False
selected_df_data.isnull().any()


survived    False
name        False
pclass      False
sex         False
age          True
sibsp       False
parch       False
fare         True
embarked     True
dtype: bool

In [9]:
#将列中为空的个数统计出来
selected_df_data.isnull().sum()

survived      0
name          0
pclass        0
sex           0
age         263
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [10]:
# 显示存在缺失值的行列，确定缺失位置
selected_df_data[selected_df_data.isnull().values==True]

survived                                               name  pclass  \
15           0                                Baumann, Mr. John D       1   
37           1      Bradley, Mr. George ("George Arthur Brayton")       1   
40           0                          Brewe, Dr. Arthur Jackson       1   
46           0                              Cairns, Mr. Alexander       1   
59           1  Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...       1   
...        ...                                                ...     ...   
1293         0                  Williams, Mr. Howard Hugh "Harry"       3   
1297         0                             Wiseman, Mr. Phillippe       3   
1302         0                                  Yousif, Mr. Wazli       3   
1303         0                              Yousseff, Mr. Gerious       3   
1305         0                              Zabour, Miss. Thamine       3   

         sex  age  sibsp  parch     fare embarked  
15      male  NaN      0      0  25.9250        S  
37      male  NaN      0      0  26.5500        S  
40      male  NaN      0      0  39.6000        C  
46      male  NaN      0      0  31.0000        S  
59    female  NaN      0      0  27.7208        C  
...      ...  ...    ...    ...      ...      ...  
1293    male  NaN      0      0   8.0500        S  
1297    male  NaN      0      0   7.2500        S  
1302    male  NaN      0      0   7.2250        C  
1303    male  NaN      0      0  14.4583        C  
1305  female  NaN      1      0  14.4542        C  

[266 rows x 9 columns]

In [11]:
# 为缺失age记录填充值，设置平均值
age_mean_value=selected_df_data['age'].mean()
selected_df_data['age']=selected_df_data['age'].fillna(age_mean_value)
# 微缺失fare记录填充值
fare_mean_value=selected_df_data['fare'].mean()
selected_df_data['fare']=selected_df_data['fare'].fillna(fare_mean_value)
# 我确实embarked记录填充值
selected_df_data['embarked']=selected_df_data['embarked'].fillna('S')

D:\anaconda\anaconda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
D:\anaconda\anaconda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\anaconda\anaconda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using

# 编码转换

In [12]:
# 性别sex字符串转为数字编码
selected_df_data['sex']=selected_df_data['sex'].map({'female':0,'male':1}).astype(int)
# 港口embarked由字母转为数字编码
selected_df_data['embarked']=selected_df_data['embarked'].map({'C':0,'Q':1,"S":2}).astype(int)

D:\anaconda\anaconda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\anaconda\anaconda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [13]:
selected_df_data[:3]

survived                            name  pclass  sex      age  sibsp  \
0         1   Allen, Miss. Elisabeth Walton       1    0  29.0000      0   
1         1  Allison, Master. Hudson Trevor       1    1   0.9167      1   
2         0    Allison, Miss. Helen Loraine       1    0   2.0000      1   

   parch      fare  embarked  
0      0  211.3375         2  
1      2  151.5500         2  
2      2  151.5500         2

# 删除name字段

In [14]:
#drop不改变df中数据，而是返回另一个DataFrame来存放删除后数据
#axis=1表示删除列
selected_df_data=selected_df_data.drop(['name'],axis=1)

In [15]:
selected_df_data[:3]

survived  pclass  sex      age  sibsp  parch      fare  embarked
0         1       1    0  29.0000      0      0  211.3375         2
1         1       1    1   0.9167      1      2  151.5500         2
2         0       1    0   2.0000      1      2  151.5500         2

# 分离特征值和标签值

In [16]:
# 转换为ndarray数组
ndarray_data=selected_df_data.values
# 后7列是特征值
features=ndarray_data[:,1:]
# 第0列是标签
label=ndarray_data[:,0]

In [17]:
features[:3]

array([[  1.    ,   0.    ,  29.    ,   0.    ,   0.    , 211.3375,
          2.    ],
       [  1.    ,   1.    ,   0.9167,   1.    ,   2.    , 151.55  ,
          2.    ],
       [  1.    ,   0.    ,   2.    ,   1.    ,   2.    , 151.55  ,
          2.    ]])

In [18]:
label[:3]

array([1., 1., 0.])

# 特征值标准化处理

In [19]:
from sklearn import preprocessing
minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
norm_features=minmax_scale.fit_transform(features)


In [20]:
norm_features[:3]

array([[0.        , 0.        , 0.36116884, 0.        , 0.        ,
        0.41250333, 1.        ],
       [0.        , 1.        , 0.00939458, 0.125     , 0.22222222,
        0.2958059 , 1.        ],
       [0.        , 0.        , 0.0229641 , 0.125     , 0.22222222,
        0.2958059 , 1.        ]])

# 定义数据预处理

In [21]:
def prepare_data(df_data):
    df=selected_df_data.drop(['name'],axis=1)
    age_mean=df['age'].mean()
    df['age']=df['age'].fillna(age_mean)
    fare_mean=df['fare'].mean()
    df['fare']=df['fare'].fillna(fare_mean)
    df['sex']=df['sex'].map({'female':0,'male':1}).astype(int)
    df['embarked']=df['embarked'].fillna('S')
    df['embarked']=df['embarked'].map({'C':0,'Q':1,'S':2}).astpe(int)
    ndarray_df.values
    features=ndarray_data[:,1:]
    label=ndarray_data[:,0]
    minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
    norm_features=minmax_scale.fit_transform(features)
    return norm_features,label

# shuffle 打乱数据顺序，为后面训练做准备

In [22]:
# shuffle打乱数据顺序，通过pandas的抽样函数sample实现，frac为百分比
# selected_df_data数据保持不变
shuffled_df_data=selected_df_data.sample(frac=1)