In [1]:
import numpy as np

# 数学对象

In [2]:
#标量只是一个单一的数字
scalar_value=18

In [3]:
print(scalar_value)

18


In [5]:
print(scalar_value,scalar_value.shape)#'int' object has no attribute 'shape'

AttributeError: 'int' object has no attribute 'shape'

In [6]:
#标量只是一个单一的数字
scalar_value=18
scalar_np=np.array(scalar_value)#转换数组中的np.array
print(scalar_np,scalar_np.shape)#shape是numpy中的概念，这里一个int数就是空

18 ()


In [7]:
#向量有序数字数组
vector_value=[1,2,3]
vector_np=np.array(vector_value)
print(vector_np,vector_np.shape)#shape显示为1维向量，但其实既不是行向量也不是列向量

[1 2 3] (3,)


In [10]:
#矩阵是个有序二维数组，一个指向行一个指向列
matrix_list=[[1,2,3],[4,5,6]]
matrix_np=np.array(matrix_list)
print("matrix_list=",matrix_list,"\n","matrix_np=\n",matrix_np,"\n","matrix_np.shape=",matrix_np.shape)

matrix_list= [[1, 2, 3], [4, 5, 6]] 
 matrix_np=
 [[1 2 3]
 [4 5 6]] 
 matrix_np.shape= (2, 3)


In [21]:
#行向量的矩阵表示
vector_row= np.array([[1,2, 3]])
print (vector_row,'shape=',vector_row.shape)

[[1 2 3]] shape= (1, 3)


In [22]:
#列向量的矩阵表示
vector_column= np.array([[4],[5], [6]])
print (vector_column,'shape=',vector_column.shape)

[[4]
 [5]
 [6]] shape= (3, 1)


In [27]:
#矩阵与标量运算
matrix_a= np.array([[1,2,3], [4, 5,6]])
print (matrix_a,'shape=',matrix_a. shape)


[[1 2 3]
 [4 5 6]] shape= (2, 3)
