In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)                           # 显示一下矩阵b
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0] )  # Prints "1 2 4"

In [2]:
import numpy as np
a=np.array([1,2])
b=np.array([[1],[2]])
print(a.shape)
print(b.shape)

(2,)
(2, 1)


In [3]:
import numpy as np

a = np.zeros((2,2))  # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"

b = np.ones((1,2))   # Create an array of all ones
print (b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7) # Create a constant array
print (c)               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

d = np.eye(2)        # Create a 2x2 identity matrix
print (d)              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
print (e)                     # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.40072714 0.27037741]
 [0.23990788 0.96640008]]


In [3]:
import numpy as np
a=[[1,2],[3,4]]
b=np.concatenate(a)

In [4]:
b

array([1, 2, 3, 4])

In [5]:
a=np.array([1,2,3])
b=np.array([11,232,33])
c=np.array([424,553,626])
d= np.concatenate((a,b,c),axis=0)  # 默认情况下，axis=0可以不写


In [6]:
d

array([  1,   2,   3,  11, 232,  33, 424, 553, 626])

# np.flatnonzero

In [13]:
a=[1,3,2,4,5,3,4,3]
b=np.flatnonzero(a==3)

In [14]:
b

array([], dtype=int64)

# 数组取一维

In [16]:
a=np.array([[1,2],[3,2],[4,2]])

In [17]:
a[1]

array([3, 2])

# np.zeros

In [52]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a.shape[0]
d=b.shape[0]

In [53]:
c

2

In [55]:
dists=np.zeros((2,2))
for i in  range(2):
    dists[i,:]=np.sum(np.square(a-b[i,:]),axis=1)
    

In [56]:
dists

array([[32.,  8.],
       [72., 32.]])

# np.sum

In [35]:
a = np.array([[0, 1, 2]]) 
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))


3
[0 1 2]
[3]


# np.hstack

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))

In [3]:
c

array([1, 2, 3, 4, 5, 6])

In [4]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [5]:
c=np.hstack((a,b))

In [6]:
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# ones asarray array


In [3]:
import numpy as np
a=np.ones((3,3))

In [4]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
b=np.array(a)

In [7]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
c=np.asarray(a)

In [9]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
a[1]=2

In [11]:
a

array([[1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [12]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
c

array([[1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 1.]])

# mean平均值

In [16]:
import numpy as np
a=np.ones((3,3))
b=a.mean(axis=(0, 1), keepdims=True)

In [17]:
b

array([[1.]])

In [18]:
c=a.mean(axis=(0, 1))

In [19]:
c

1.0

In [23]:
d=np.ones((3,3,3))
e=d.mean(axis=(0,1,2),keepdims=True)

In [24]:
e

array([[[1.]]])

# numpy的np.random.shuffle


np.random,shuffle作用就是重新排序返回一个随机序列作用类似洗牌

In [5]:
import numpy as np
test_arr1=np.arange(10)
np.random.shuffle(test_arr1)


In [6]:
test_arr1

array([0, 6, 1, 8, 9, 2, 4, 7, 3, 5])

就是对第一维度进行随机打乱

In [7]:
test_arr2=np.arange(12).reshape(3,4)

In [8]:
test_arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.random.shuffle(test_arr2)

In [10]:
test_arr2

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])